server:
  port: 8081

spring:
  application:
    name: client-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: clientdb

logging:
  level:
    root: INFO
    br.com.nebulastar.clientservice: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs
