# Basic PostgreSQL Config
spring.datasource.url=jdbc:postgresql://localhost:15432/vendas_online_spring
spring.datasource.username=postgres
spring.datasource.password=stardust
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
